/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.joda.time.DateTime;

/**
 * The BatchStatus model.
 */
public class BatchStatus {
    /**
     * The resourceId property.
     */
    @JsonProperty(value = "resourceId")
    private String resourceId;

    /**
     * The updatedAt property.
     */
    @JsonProperty(value = "updatedAt")
    private DateTime updatedAt;

    /**
     * The updatedBy property.
     */
    @JsonProperty(value = "updatedBy")
    private String updatedBy;

    /**
     * The goBetweenAgent property.
     */
    @JsonProperty(value = "goBetweenAgent")
    private BatchStatusGoBetweenScope goBetweenAgent;

    /**
     * Get the resourceId value.
     *
     * @return the resourceId value
     */
    public String resourceId() {
        return this.resourceId;
    }

    /**
     * Set the resourceId value.
     *
     * @param resourceId the resourceId value to set
     * @return the BatchStatus object itself.
     */
    public BatchStatus withResourceId(String resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    /**
     * Get the updatedAt value.
     *
     * @return the updatedAt value
     */
    public DateTime updatedAt() {
        return this.updatedAt;
    }

    /**
     * Set the updatedAt value.
     *
     * @param updatedAt the updatedAt value to set
     * @return the BatchStatus object itself.
     */
    public BatchStatus withUpdatedAt(DateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Get the updatedBy value.
     *
     * @return the updatedBy value
     */
    public String updatedBy() {
        return this.updatedBy;
    }

    /**
     * Set the updatedBy value.
     *
     * @param updatedBy the updatedBy value to set
     * @return the BatchStatus object itself.
     */
    public BatchStatus withUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Get the goBetweenAgent value.
     *
     * @return the goBetweenAgent value
     */
    public BatchStatusGoBetweenScope goBetweenAgent() {
        return this.goBetweenAgent;
    }

    /**
     * Set the goBetweenAgent value.
     *
     * @param goBetweenAgent the goBetweenAgent value to set
     * @return the BatchStatus object itself.
     */
    public BatchStatus withGoBetweenAgent(BatchStatusGoBetweenScope goBetweenAgent) {
        this.goBetweenAgent = goBetweenAgent;
        return this;
    }

}
