/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The FilterRule model.
 */
public class FilterRule {
    /**
     * Possible values include: 'include', 'exclude'.
     */
    @JsonProperty(value = "effect")
    private FilterRuleEffect effect;

    /**
     * The propertyId property.
     */
    @JsonProperty(value = "propertyId")
    private String propertyId;

    /**
     * The operatorId property.
     */
    @JsonProperty(value = "operatorId")
    private String operatorId;

    /**
     * The parameter property.
     */
    @JsonProperty(value = "parameter")
    private Object parameter;

    /**
     * Get possible values include: 'include', 'exclude'.
     *
     * @return the effect value
     */
    public FilterRuleEffect effect() {
        return this.effect;
    }

    /**
     * Set possible values include: 'include', 'exclude'.
     *
     * @param effect the effect value to set
     * @return the FilterRule object itself.
     */
    public FilterRule withEffect(FilterRuleEffect effect) {
        this.effect = effect;
        return this;
    }

    /**
     * Get the propertyId value.
     *
     * @return the propertyId value
     */
    public String propertyId() {
        return this.propertyId;
    }

    /**
     * Set the propertyId value.
     *
     * @param propertyId the propertyId value to set
     * @return the FilterRule object itself.
     */
    public FilterRule withPropertyId(String propertyId) {
        this.propertyId = propertyId;
        return this;
    }

    /**
     * Get the operatorId value.
     *
     * @return the operatorId value
     */
    public String operatorId() {
        return this.operatorId;
    }

    /**
     * Set the operatorId value.
     *
     * @param operatorId the operatorId value to set
     * @return the FilterRule object itself.
     */
    public FilterRule withOperatorId(String operatorId) {
        this.operatorId = operatorId;
        return this;
    }

    /**
     * Get the parameter value.
     *
     * @return the parameter value
     */
    public Object parameter() {
        return this.parameter;
    }

    /**
     * Set the parameter value.
     *
     * @param parameter the parameter value to set
     * @return the FilterRule object itself.
     */
    public FilterRule withParameter(Object parameter) {
        this.parameter = parameter;
        return this;
    }

}
