/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.joda.time.DateTime;

import java.util.List;

/**
 * The Job model.
 */
public class Job {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The version property.
     */
    @JsonProperty(value = "version")
    private Integer version;

    /**
     * The name property.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The description property.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * The schedule property.
     */
    @JsonProperty(value = "schedule")
    private Schedule schedule;

    /**
     * The connectionId property.
     */
    @JsonProperty(value = "connectionId")
    private String connectionId;

    /**
     * The schemaId property.
     */
    @JsonProperty(value = "schemaId")
    private String schemaId;

    /**
     * The shapeId property.
     */
    @JsonProperty(value = "shapeId")
    private String shapeId;

    /**
     * The agentId property.
     */
    @JsonProperty(value = "agentId")
    private String agentId;

    /**
     * The canRunInCloud property.
     */
    @JsonProperty(value = "canRunInCloud")
    private Boolean canRunInCloud;

    /**
     * The dataVersion property.
     */
    @JsonProperty(value = "dataVersion")
    private Integer dataVersion;

    /**
     * The propertyMappings property.
     */
    @JsonProperty(value = "propertyMappings")
    private List<PropertyMapping> propertyMappings;

    /**
     * Possible values include: 'read', 'write', 'profiling', 'qualityCheck'.
     */
    @JsonProperty(value = "type")
    private JobType type;

    /**
     * The isPaused property.
     */
    @JsonProperty(value = "isPaused")
    private Boolean isPaused;

    /**
     * The writeback property.
     */
    @JsonProperty(value = "writeback")
    private Writeback writeback;

    /**
     * The filter property.
     */
    @JsonProperty(value = "filter")
    private Filter filter;

    /**
     * The status property.
     */
    @JsonProperty(value = "status")
    private JobStatus status;

    /**
     * The latestBatch property.
     */
    @JsonProperty(value = "latestBatch")
    private Batch latestBatch;

    /**
     * The createdAt property.
     */
    @JsonProperty(value = "createdAt")
    private DateTime createdAt;

    /**
     * The createdBy property.
     */
    @JsonProperty(value = "createdBy")
    private String createdBy;

    /**
     * The updatedAt property.
     */
    @JsonProperty(value = "updatedAt")
    private DateTime updatedAt;

    /**
     * The updatedBy property.
     */
    @JsonProperty(value = "updatedBy")
    private String updatedBy;

    /**
     * The deletedAt property.
     */
    @JsonProperty(value = "deletedAt")
    private DateTime deletedAt;

    /**
     * The deletedBy property.
     */
    @JsonProperty(value = "deletedBy")
    private String deletedBy;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Job object itself.
     */
    public Job withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the version value.
     *
     * @return the version value
     */
    public Integer version() {
        return this.version;
    }

    /**
     * Set the version value.
     *
     * @param version the version value to set
     * @return the Job object itself.
     */
    public Job withVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Job object itself.
     */
    public Job withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the Job object itself.
     */
    public Job withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the schedule value.
     *
     * @return the schedule value
     */
    public Schedule schedule() {
        return this.schedule;
    }

    /**
     * Set the schedule value.
     *
     * @param schedule the schedule value to set
     * @return the Job object itself.
     */
    public Job withSchedule(Schedule schedule) {
        this.schedule = schedule;
        return this;
    }

    /**
     * Get the connectionId value.
     *
     * @return the connectionId value
     */
    public String connectionId() {
        return this.connectionId;
    }

    /**
     * Set the connectionId value.
     *
     * @param connectionId the connectionId value to set
     * @return the Job object itself.
     */
    public Job withConnectionId(String connectionId) {
        this.connectionId = connectionId;
        return this;
    }

    /**
     * Get the schemaId value.
     *
     * @return the schemaId value
     */
    public String schemaId() {
        return this.schemaId;
    }

    /**
     * Set the schemaId value.
     *
     * @param schemaId the schemaId value to set
     * @return the Job object itself.
     */
    public Job withSchemaId(String schemaId) {
        this.schemaId = schemaId;
        return this;
    }

    /**
     * Get the shapeId value.
     *
     * @return the shapeId value
     */
    public String shapeId() {
        return this.shapeId;
    }

    /**
     * Set the shapeId value.
     *
     * @param shapeId the shapeId value to set
     * @return the Job object itself.
     */
    public Job withShapeId(String shapeId) {
        this.shapeId = shapeId;
        return this;
    }

    /**
     * Get the agentId value.
     *
     * @return the agentId value
     */
    public String agentId() {
        return this.agentId;
    }

    /**
     * Set the agentId value.
     *
     * @param agentId the agentId value to set
     * @return the Job object itself.
     */
    public Job withAgentId(String agentId) {
        this.agentId = agentId;
        return this;
    }

    /**
     * Get the canRunInCloud value.
     *
     * @return the canRunInCloud value
     */
    public Boolean canRunInCloud() {
        return this.canRunInCloud;
    }

    /**
     * Set the canRunInCloud value.
     *
     * @param canRunInCloud the canRunInCloud value to set
     * @return the Job object itself.
     */
    public Job withCanRunInCloud(Boolean canRunInCloud) {
        this.canRunInCloud = canRunInCloud;
        return this;
    }

    /**
     * Get the dataVersion value.
     *
     * @return the dataVersion value
     */
    public Integer dataVersion() {
        return this.dataVersion;
    }

    /**
     * Set the dataVersion value.
     *
     * @param dataVersion the dataVersion value to set
     * @return the Job object itself.
     */
    public Job withDataVersion(Integer dataVersion) {
        this.dataVersion = dataVersion;
        return this;
    }

    /**
     * Get the propertyMappings value.
     *
     * @return the propertyMappings value
     */
    public List<PropertyMapping> propertyMappings() {
        return this.propertyMappings;
    }

    /**
     * Set the propertyMappings value.
     *
     * @param propertyMappings the propertyMappings value to set
     * @return the Job object itself.
     */
    public Job withPropertyMappings(List<PropertyMapping> propertyMappings) {
        this.propertyMappings = propertyMappings;
        return this;
    }

    /**
     * Get possible values include: 'read', 'write', 'profiling', 'qualityCheck'.
     *
     * @return the type value
     */
    public JobType type() {
        return this.type;
    }

    /**
     * Set possible values include: 'read', 'write', 'profiling', 'qualityCheck'.
     *
     * @param type the type value to set
     * @return the Job object itself.
     */
    public Job withType(JobType type) {
        this.type = type;
        return this;
    }

    /**
     * Get the isPaused value.
     *
     * @return the isPaused value
     */
    public Boolean isPaused() {
        return this.isPaused;
    }

    /**
     * Set the isPaused value.
     *
     * @param isPaused the isPaused value to set
     * @return the Job object itself.
     */
    public Job withIsPaused(Boolean isPaused) {
        this.isPaused = isPaused;
        return this;
    }

    /**
     * Get the writeback value.
     *
     * @return the writeback value
     */
    public Writeback writeback() {
        return this.writeback;
    }

    /**
     * Set the writeback value.
     *
     * @param writeback the writeback value to set
     * @return the Job object itself.
     */
    public Job withWriteback(Writeback writeback) {
        this.writeback = writeback;
        return this;
    }

    /**
     * Get the filter value.
     *
     * @return the filter value
     */
    public Filter filter() {
        return this.filter;
    }

    /**
     * Set the filter value.
     *
     * @param filter the filter value to set
     * @return the Job object itself.
     */
    public Job withFilter(Filter filter) {
        this.filter = filter;
        return this;
    }

    /**
     * Get the status value.
     *
     * @return the status value
     */
    public JobStatus status() {
        return this.status;
    }

    /**
     * Set the status value.
     *
     * @param status the status value to set
     * @return the Job object itself.
     */
    public Job withStatus(JobStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Get the latestBatch value.
     *
     * @return the latestBatch value
     */
    public Batch latestBatch() {
        return this.latestBatch;
    }

    /**
     * Set the latestBatch value.
     *
     * @param latestBatch the latestBatch value to set
     * @return the Job object itself.
     */
    public Job withLatestBatch(Batch latestBatch) {
        this.latestBatch = latestBatch;
        return this;
    }

    /**
     * Get the createdAt value.
     *
     * @return the createdAt value
     */
    public DateTime createdAt() {
        return this.createdAt;
    }

    /**
     * Set the createdAt value.
     *
     * @param createdAt the createdAt value to set
     * @return the Job object itself.
     */
    public Job withCreatedAt(DateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Get the createdBy value.
     *
     * @return the createdBy value
     */
    public String createdBy() {
        return this.createdBy;
    }

    /**
     * Set the createdBy value.
     *
     * @param createdBy the createdBy value to set
     * @return the Job object itself.
     */
    public Job withCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get the updatedAt value.
     *
     * @return the updatedAt value
     */
    public DateTime updatedAt() {
        return this.updatedAt;
    }

    /**
     * Set the updatedAt value.
     *
     * @param updatedAt the updatedAt value to set
     * @return the Job object itself.
     */
    public Job withUpdatedAt(DateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Get the updatedBy value.
     *
     * @return the updatedBy value
     */
    public String updatedBy() {
        return this.updatedBy;
    }

    /**
     * Set the updatedBy value.
     *
     * @param updatedBy the updatedBy value to set
     * @return the Job object itself.
     */
    public Job withUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Get the deletedAt value.
     *
     * @return the deletedAt value
     */
    public DateTime deletedAt() {
        return this.deletedAt;
    }

    /**
     * Set the deletedAt value.
     *
     * @param deletedAt the deletedAt value to set
     * @return the Job object itself.
     */
    public Job withDeletedAt(DateTime deletedAt) {
        this.deletedAt = deletedAt;
        return this;
    }

    /**
     * Get the deletedBy value.
     *
     * @return the deletedBy value
     */
    public String deletedBy() {
        return this.deletedBy;
    }

    /**
     * Set the deletedBy value.
     *
     * @param deletedBy the deletedBy value to set
     * @return the Job object itself.
     */
    public Job withDeletedBy(String deletedBy) {
        this.deletedBy = deletedBy;
        return this;
    }

}
