/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.joda.time.DateTime;

/**
 * The JobStatusGoBetweenScope model.
 */
public class JobStatusGoBetweenScope {
    /**
     * The resourceId property.
     */
    @JsonProperty(value = "resourceId")
    private String resourceId;

    /**
     * The updatedAt property.
     */
    @JsonProperty(value = "updatedAt")
    private DateTime updatedAt;

    /**
     * The updatedBy property.
     */
    @JsonProperty(value = "updatedBy")
    private String updatedBy;

    /**
     * The error property.
     */
    @JsonProperty(value = "error")
    private String error;

    /**
     * The message property.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * The startCount property.
     */
    @JsonProperty(value = "startCount")
    private Integer startCount;

    /**
     * The successCount property.
     */
    @JsonProperty(value = "successCount")
    private Integer successCount;

    /**
     * The consecutiveFailureCount property.
     */
    @JsonProperty(value = "consecutiveFailureCount")
    private Integer consecutiveFailureCount;

    /**
     * The state property.
     */
    @JsonProperty(value = "state")
    private String state;

    /**
     * The nextRunAt property.
     */
    @JsonProperty(value = "nextRunAt")
    private DateTime nextRunAt;

    /**
     * The previousRunAt property.
     */
    @JsonProperty(value = "previousRunAt")
    private DateTime previousRunAt;

    /**
     * The scheduledOn property.
     */
    @JsonProperty(value = "scheduledOn")
    private String scheduledOn;

    /**
     * The scheduledAt property.
     */
    @JsonProperty(value = "scheduledAt")
    private DateTime scheduledAt;

    /**
     * Get the resourceId value.
     *
     * @return the resourceId value
     */
    public String resourceId() {
        return this.resourceId;
    }

    /**
     * Set the resourceId value.
     *
     * @param resourceId the resourceId value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withResourceId(String resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    /**
     * Get the updatedAt value.
     *
     * @return the updatedAt value
     */
    public DateTime updatedAt() {
        return this.updatedAt;
    }

    /**
     * Set the updatedAt value.
     *
     * @param updatedAt the updatedAt value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withUpdatedAt(DateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Get the updatedBy value.
     *
     * @return the updatedBy value
     */
    public String updatedBy() {
        return this.updatedBy;
    }

    /**
     * Set the updatedBy value.
     *
     * @param updatedBy the updatedBy value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Get the error value.
     *
     * @return the error value
     */
    public String error() {
        return this.error;
    }

    /**
     * Set the error value.
     *
     * @param error the error value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withError(String error) {
        this.error = error;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the startCount value.
     *
     * @return the startCount value
     */
    public Integer startCount() {
        return this.startCount;
    }

    /**
     * Set the startCount value.
     *
     * @param startCount the startCount value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withStartCount(Integer startCount) {
        this.startCount = startCount;
        return this;
    }

    /**
     * Get the successCount value.
     *
     * @return the successCount value
     */
    public Integer successCount() {
        return this.successCount;
    }

    /**
     * Set the successCount value.
     *
     * @param successCount the successCount value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withSuccessCount(Integer successCount) {
        this.successCount = successCount;
        return this;
    }

    /**
     * Get the consecutiveFailureCount value.
     *
     * @return the consecutiveFailureCount value
     */
    public Integer consecutiveFailureCount() {
        return this.consecutiveFailureCount;
    }

    /**
     * Set the consecutiveFailureCount value.
     *
     * @param consecutiveFailureCount the consecutiveFailureCount value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withConsecutiveFailureCount(Integer consecutiveFailureCount) {
        this.consecutiveFailureCount = consecutiveFailureCount;
        return this;
    }

    /**
     * Get the state value.
     *
     * @return the state value
     */
    public String state() {
        return this.state;
    }

    /**
     * Set the state value.
     *
     * @param state the state value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Get the nextRunAt value.
     *
     * @return the nextRunAt value
     */
    public DateTime nextRunAt() {
        return this.nextRunAt;
    }

    /**
     * Set the nextRunAt value.
     *
     * @param nextRunAt the nextRunAt value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withNextRunAt(DateTime nextRunAt) {
        this.nextRunAt = nextRunAt;
        return this;
    }

    /**
     * Get the previousRunAt value.
     *
     * @return the previousRunAt value
     */
    public DateTime previousRunAt() {
        return this.previousRunAt;
    }

    /**
     * Set the previousRunAt value.
     *
     * @param previousRunAt the previousRunAt value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withPreviousRunAt(DateTime previousRunAt) {
        this.previousRunAt = previousRunAt;
        return this;
    }

    /**
     * Get the scheduledOn value.
     *
     * @return the scheduledOn value
     */
    public String scheduledOn() {
        return this.scheduledOn;
    }

    /**
     * Set the scheduledOn value.
     *
     * @param scheduledOn the scheduledOn value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withScheduledOn(String scheduledOn) {
        this.scheduledOn = scheduledOn;
        return this;
    }

    /**
     * Get the scheduledAt value.
     *
     * @return the scheduledAt value
     */
    public DateTime scheduledAt() {
        return this.scheduledAt;
    }

    /**
     * Set the scheduledAt value.
     *
     * @param scheduledAt the scheduledAt value to set
     * @return the JobStatusGoBetweenScope object itself.
     */
    public JobStatusGoBetweenScope withScheduledAt(DateTime scheduledAt) {
        this.scheduledAt = scheduledAt;
        return this;
    }

}
