/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.joda.time.DateTime;

import java.util.List;

/**
 * The Mapping model.
 */
public class Mapping {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The version property.
     */
    @JsonProperty(value = "version")
    private Integer version;

    /**
     * The name property.
     */
    @JsonProperty(value = "name", required = true)
    private String name;

    /**
     * The description property.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * Possible values include: 'schemaToShape', 'shapeToSchema'.
     */
    @JsonProperty(value = "direction")
    private MappingDirection direction;

    /**
     * The schemaId property.
     */
    @JsonProperty(value = "schemaId", required = true)
    private String schemaId;

    /**
     * The shapeId property.
     */
    @JsonProperty(value = "shapeId", required = true)
    private String shapeId;

    /**
     * The propertyMappings property.
     */
    @JsonProperty(value = "propertyMappings", required = true)
    private List<PropertyMapping> propertyMappings;

    /**
     * The createdAt property.
     */
    @JsonProperty(value = "createdAt")
    private DateTime createdAt;

    /**
     * The createdBy property.
     */
    @JsonProperty(value = "createdBy")
    private String createdBy;

    /**
     * The updatedAt property.
     */
    @JsonProperty(value = "updatedAt")
    private DateTime updatedAt;

    /**
     * The updatedBy property.
     */
    @JsonProperty(value = "updatedBy")
    private String updatedBy;

    /**
     * The deletedAt property.
     */
    @JsonProperty(value = "deletedAt")
    private DateTime deletedAt;

    /**
     * The deletedBy property.
     */
    @JsonProperty(value = "deletedBy")
    private String deletedBy;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Mapping object itself.
     */
    public Mapping withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the version value.
     *
     * @return the version value
     */
    public Integer version() {
        return this.version;
    }

    /**
     * Set the version value.
     *
     * @param version the version value to set
     * @return the Mapping object itself.
     */
    public Mapping withVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Mapping object itself.
     */
    public Mapping withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the Mapping object itself.
     */
    public Mapping withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get possible values include: 'schemaToShape', 'shapeToSchema'.
     *
     * @return the direction value
     */
    public MappingDirection direction() {
        return this.direction;
    }

    /**
     * Set possible values include: 'schemaToShape', 'shapeToSchema'.
     *
     * @param direction the direction value to set
     * @return the Mapping object itself.
     */
    public Mapping withDirection(MappingDirection direction) {
        this.direction = direction;
        return this;
    }

    /**
     * Get the schemaId value.
     *
     * @return the schemaId value
     */
    public String schemaId() {
        return this.schemaId;
    }

    /**
     * Set the schemaId value.
     *
     * @param schemaId the schemaId value to set
     * @return the Mapping object itself.
     */
    public Mapping withSchemaId(String schemaId) {
        this.schemaId = schemaId;
        return this;
    }

    /**
     * Get the shapeId value.
     *
     * @return the shapeId value
     */
    public String shapeId() {
        return this.shapeId;
    }

    /**
     * Set the shapeId value.
     *
     * @param shapeId the shapeId value to set
     * @return the Mapping object itself.
     */
    public Mapping withShapeId(String shapeId) {
        this.shapeId = shapeId;
        return this;
    }

    /**
     * Get the propertyMappings value.
     *
     * @return the propertyMappings value
     */
    public List<PropertyMapping> propertyMappings() {
        return this.propertyMappings;
    }

    /**
     * Set the propertyMappings value.
     *
     * @param propertyMappings the propertyMappings value to set
     * @return the Mapping object itself.
     */
    public Mapping withPropertyMappings(List<PropertyMapping> propertyMappings) {
        this.propertyMappings = propertyMappings;
        return this;
    }

    /**
     * Get the createdAt value.
     *
     * @return the createdAt value
     */
    public DateTime createdAt() {
        return this.createdAt;
    }

    /**
     * Set the createdAt value.
     *
     * @param createdAt the createdAt value to set
     * @return the Mapping object itself.
     */
    public Mapping withCreatedAt(DateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Get the createdBy value.
     *
     * @return the createdBy value
     */
    public String createdBy() {
        return this.createdBy;
    }

    /**
     * Set the createdBy value.
     *
     * @param createdBy the createdBy value to set
     * @return the Mapping object itself.
     */
    public Mapping withCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get the updatedAt value.
     *
     * @return the updatedAt value
     */
    public DateTime updatedAt() {
        return this.updatedAt;
    }

    /**
     * Set the updatedAt value.
     *
     * @param updatedAt the updatedAt value to set
     * @return the Mapping object itself.
     */
    public Mapping withUpdatedAt(DateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * Get the updatedBy value.
     *
     * @return the updatedBy value
     */
    public String updatedBy() {
        return this.updatedBy;
    }

    /**
     * Set the updatedBy value.
     *
     * @param updatedBy the updatedBy value to set
     * @return the Mapping object itself.
     */
    public Mapping withUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Get the deletedAt value.
     *
     * @return the deletedAt value
     */
    public DateTime deletedAt() {
        return this.deletedAt;
    }

    /**
     * Set the deletedAt value.
     *
     * @param deletedAt the deletedAt value to set
     * @return the Mapping object itself.
     */
    public Mapping withDeletedAt(DateTime deletedAt) {
        this.deletedAt = deletedAt;
        return this;
    }

    /**
     * Get the deletedBy value.
     *
     * @return the deletedBy value
     */
    public String deletedBy() {
        return this.deletedBy;
    }

    /**
     * Set the deletedBy value.
     *
     * @param deletedBy the deletedBy value to set
     * @return the Mapping object itself.
     */
    public Mapping withDeletedBy(String deletedBy) {
        this.deletedBy = deletedBy;
        return this;
    }

}
