/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Map;

/**
 * The MergeRule model.
 */
public class MergeRule {
    /**
     * The version property.
     */
    @JsonProperty(value = "version")
    private Integer version;

    /**
     * The properties property.
     */
    @JsonProperty(value = "properties")
    private Map<String, PropertyMergeRule> properties;

    /**
     * Get the version value.
     *
     * @return the version value
     */
    public Integer version() {
        return this.version;
    }

    /**
     * Set the version value.
     *
     * @param version the version value to set
     * @return the MergeRule object itself.
     */
    public MergeRule withVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Get the properties value.
     *
     * @return the properties value
     */
    public Map<String, PropertyMergeRule> properties() {
        return this.properties;
    }

    /**
     * Set the properties value.
     *
     * @param properties the properties value to set
     * @return the MergeRule object itself.
     */
    public MergeRule withProperties(Map<String, PropertyMergeRule> properties) {
        this.properties = properties;
        return this;
    }

}
