// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * This package contains the models classes for MetabaseAPI10.
 * API surface for Metabase. Application version is 0.0.0. NRN is nv1:n5o.red::metabase:self/metabase-7f74b97897-654n8@0.0.0.
 */
package com.naveego.metabase.models;
