/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * The PagedResultOfJobStatus model.
 */
public class PagedResultOfJobStatus {
    /**
     * The pageSize property.
     */
    @JsonProperty(value = "pageSize")
    private Integer pageSize;

    /**
     * The currentPage property.
     */
    @JsonProperty(value = "currentPage")
    private Long currentPage;

    /**
     * The totalItems property.
     */
    @JsonProperty(value = "totalItems")
    private Long totalItems;

    /**
     * The items property.
     */
    @JsonProperty(value = "items")
    private List<JobStatus> items;

    /**
     * Get the pageSize value.
     *
     * @return the pageSize value
     */
    public Integer pageSize() {
        return this.pageSize;
    }

    /**
     * Set the pageSize value.
     *
     * @param pageSize the pageSize value to set
     * @return the PagedResultOfJobStatus object itself.
     */
    public PagedResultOfJobStatus withPageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /**
     * Get the currentPage value.
     *
     * @return the currentPage value
     */
    public Long currentPage() {
        return this.currentPage;
    }

    /**
     * Set the currentPage value.
     *
     * @param currentPage the currentPage value to set
     * @return the PagedResultOfJobStatus object itself.
     */
    public PagedResultOfJobStatus withCurrentPage(Long currentPage) {
        this.currentPage = currentPage;
        return this;
    }

    /**
     * Get the totalItems value.
     *
     * @return the totalItems value
     */
    public Long totalItems() {
        return this.totalItems;
    }

    /**
     * Set the totalItems value.
     *
     * @param totalItems the totalItems value to set
     * @return the PagedResultOfJobStatus object itself.
     */
    public PagedResultOfJobStatus withTotalItems(Long totalItems) {
        this.totalItems = totalItems;
        return this;
    }

    /**
     * Get the items value.
     *
     * @return the items value
     */
    public List<JobStatus> items() {
        return this.items;
    }

    /**
     * Set the items value.
     *
     * @param items the items value to set
     * @return the PagedResultOfJobStatus object itself.
     */
    public PagedResultOfJobStatus withItems(List<JobStatus> items) {
        this.items = items;
        return this;
    }

}
