/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Payload model.
 */
public class Payload {
    /**
     * The m property.
     */
    @JsonProperty(value = "m")
    private Object m;

    /**
     * Get the m value.
     *
     * @return the m value
     */
    public Object m() {
        return this.m;
    }

    /**
     * Set the m value.
     *
     * @param m the m value to set
     * @return the Payload object itself.
     */
    public Payload withM(Object m) {
        this.m = m;
        return this;
    }

}
