/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

import java.util.Collection;

/**
 * Defines values for ScheduleType.
 */
public final class ScheduleType extends ExpandableStringEnum<ScheduleType> {
    /** Static value never for ScheduleType. */
    public static final ScheduleType NEVER = fromString("never");

    /** Static value immediate for ScheduleType. */
    public static final ScheduleType IMMEDIATE = fromString("immediate");

    /** Static value onDemand for ScheduleType. */
    public static final ScheduleType ON_DEMAND = fromString("onDemand");

    /** Static value once for ScheduleType. */
    public static final ScheduleType ONCE = fromString("once");

    /** Static value interval for ScheduleType. */
    public static final ScheduleType INTERVAL = fromString("interval");

    /** Static value cron for ScheduleType. */
    public static final ScheduleType CRON = fromString("cron");

    /** Static value realTime for ScheduleType. */
    public static final ScheduleType REAL_TIME = fromString("realTime");

    /** Static value always for ScheduleType. */
    public static final ScheduleType ALWAYS = fromString("always");

    /**
     * Creates or finds a ScheduleType from its string representation.
     * @param name a name to look for
     * @return the corresponding ScheduleType
     */
    @JsonCreator
    public static ScheduleType fromString(String name) {
        return fromString(name, ScheduleType.class);
    }

    /**
     * @return known ScheduleType values
     */
    public static Collection<ScheduleType> values() {
        return values(ScheduleType.class);
    }
}
