/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.joda.time.DateTime;

/**
 * The Trace model.
 */
public class Trace {
    /**
     * The n property.
     */
    @JsonProperty(value = "n")
    private String n;

    /**
     * The ts property.
     */
    @JsonProperty(value = "ts")
    private DateTime ts;

    /**
     * The d property.
     */
    @JsonProperty(value = "d")
    private Integer d;

    /**
     * Get the n value.
     *
     * @return the n value
     */
    public String n() {
        return this.n;
    }

    /**
     * Set the n value.
     *
     * @param n the n value to set
     * @return the Trace object itself.
     */
    public Trace withN(String n) {
        this.n = n;
        return this;
    }

    /**
     * Get the ts value.
     *
     * @return the ts value
     */
    public DateTime ts() {
        return this.ts;
    }

    /**
     * Set the ts value.
     *
     * @param ts the ts value to set
     * @return the Trace object itself.
     */
    public Trace withTs(DateTime ts) {
        this.ts = ts;
        return this;
    }

    /**
     * Get the d value.
     *
     * @return the d value
     */
    public Integer d() {
        return this.d;
    }

    /**
     * Set the d value.
     *
     * @param d the d value to set
     * @return the Trace object itself.
     */
    public Trace withD(Integer d) {
        this.d = d;
        return this;
    }

}
