/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TraitAttributeDefinition model.
 */
public class TraitAttributeDefinition {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Possible values include: 'string', 'count', 'percent', 'statistic',
     * 'details', 'histogram', 'boxplot'.
     */
    @JsonProperty(value = "type")
    private TraitAttributeType type;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the TraitAttributeDefinition object itself.
     */
    public TraitAttributeDefinition withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the TraitAttributeDefinition object itself.
     */
    public TraitAttributeDefinition withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get possible values include: 'string', 'count', 'percent', 'statistic', 'details', 'histogram', 'boxplot'.
     *
     * @return the type value
     */
    public TraitAttributeType type() {
        return this.type;
    }

    /**
     * Set possible values include: 'string', 'count', 'percent', 'statistic', 'details', 'histogram', 'boxplot'.
     *
     * @param type the type value to set
     * @return the TraitAttributeDefinition object itself.
     */
    public TraitAttributeDefinition withType(TraitAttributeType type) {
        this.type = type;
        return this;
    }

}
