/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */
export var DiscoveryKey = {
    serializedName: "DiscoveryKey",
    type: {
        name: "Composite",
        className: "DiscoveryKey",
        modelProperties: {
            alg: {
                required: true,
                serializedName: "alg",
                type: {
                    name: "String"
                }
            },
            e: {
                required: true,
                serializedName: "e",
                type: {
                    name: "String"
                }
            },
            kid: {
                required: true,
                serializedName: "kid",
                type: {
                    name: "String"
                }
            },
            kty: {
                required: true,
                serializedName: "kty",
                type: {
                    name: "String"
                }
            },
            n: {
                required: true,
                serializedName: "n",
                type: {
                    name: "String"
                }
            },
            use: {
                required: true,
                serializedName: "use",
                type: {
                    name: "String"
                }
            },
            x5c: {
                required: true,
                serializedName: "x5c",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "String"
                        }
                    }
                }
            },
            x5t: {
                required: true,
                serializedName: "x5t",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var DiscoveryKeys = {
    serializedName: "DiscoveryKeys",
    type: {
        name: "Composite",
        className: "DiscoveryKeys",
        modelProperties: {
            keys: {
                required: true,
                serializedName: "keys",
                type: {
                    name: "Sequence",
                    element: {
                        type: {
                            name: "Composite",
                            className: "DiscoveryKey"
                        }
                    }
                }
            }
        }
    }
};
export var OauthToken = {
    serializedName: "OauthToken",
    type: {
        name: "Composite",
        className: "OauthToken",
        modelProperties: {
            accessToken: {
                required: true,
                serializedName: "access_token",
                type: {
                    name: "String"
                }
            },
            expiresIn: {
                required: true,
                serializedName: "expires_in",
                type: {
                    name: "Number"
                }
            },
            id: {
                required: true,
                serializedName: "id",
                type: {
                    name: "String"
                }
            },
            issuedAt: {
                required: true,
                serializedName: "issued_at",
                type: {
                    name: "Number"
                }
            },
            refreshToken: {
                serializedName: "refresh_token",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var SamlGenerateRequestResponse = {
    serializedName: "SamlGenerateRequestResponse",
    type: {
        name: "Composite",
        className: "SamlGenerateRequestResponse",
        modelProperties: {
            relayState: {
                required: true,
                serializedName: "relay_state",
                type: {
                    name: "String"
                }
            },
            samlRequest: {
                required: true,
                serializedName: "saml_request",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var SamlSAMLSettings = {
    serializedName: "SamlSAMLSettings",
    type: {
        name: "Composite",
        className: "SamlSAMLSettings",
        modelProperties: {
            assertionConsumerServiceUrl: {
                required: true,
                serializedName: "assertion_consumer_service_url",
                type: {
                    name: "String"
                }
            },
            id: {
                required: true,
                serializedName: "id",
                type: {
                    name: "String"
                }
            },
            idpPublicCertPath: {
                required: true,
                serializedName: "idp_public_cert_path",
                type: {
                    name: "String"
                }
            },
            idpSsoDecriptorUrl: {
                required: true,
                serializedName: "idp_sso_decriptor_url",
                type: {
                    name: "String"
                }
            },
            idpSsoUrl: {
                required: true,
                serializedName: "idp_sso_url",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var TenantConfiguration = {
    serializedName: "TenantConfiguration",
    type: {
        name: "Composite",
        className: "TenantConfiguration",
        modelProperties: {
            id: {
                required: true,
                serializedName: "id",
                type: {
                    name: "String"
                }
            },
            name: {
                required: true,
                serializedName: "name",
                type: {
                    name: "String"
                }
            },
            provider: {
                required: true,
                serializedName: "provider",
                type: {
                    name: "String"
                }
            },
            providerSettings: {
                required: true,
                serializedName: "provider_settings",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var UserAuthCodeResponse = {
    serializedName: "UserAuthCodeResponse",
    type: {
        name: "Composite",
        className: "UserAuthCodeResponse",
        modelProperties: {
            code: {
                required: true,
                serializedName: "code",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var UserUser = {
    serializedName: "UserUser",
    type: {
        name: "Composite",
        className: "UserUser",
        modelProperties: {
            attributes: {
                serializedName: "attributes",
                type: {
                    name: "Dictionary",
                    value: {
                        type: {
                            name: "String"
                        }
                    }
                }
            },
            createdOn: {
                serializedName: "created_on",
                type: {
                    name: "String"
                }
            },
            id: {
                serializedName: "id",
                type: {
                    name: "String"
                }
            },
            lastTouch: {
                serializedName: "last_touch",
                type: {
                    name: "String"
                }
            },
            modifiedOn: {
                serializedName: "modified_on",
                type: {
                    name: "String"
                }
            },
            status: {
                serializedName: "status",
                type: {
                    name: "String"
                }
            },
            tenantId: {
                serializedName: "tenant_id",
                type: {
                    name: "String"
                }
            },
            username: {
                serializedName: "username",
                type: {
                    name: "String"
                }
            }
        }
    }
};
export var UserCreateUser = {
    serializedName: "UserCreateUser",
    type: {
        name: "Composite",
        className: "UserCreateUser",
        modelProperties: {
            user: {
                required: true,
                serializedName: "User",
                type: {
                    name: "Composite",
                    className: "UserUser"
                }
            }
        }
    }
};
//# sourceMappingURL=mappers.js.map