/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
export var clientId = {
    parameterPath: "clientId",
    mapper: {
        required: true,
        serializedName: "client_id",
        type: {
            name: "String"
        }
    }
};
export var code = {
    parameterPath: [
        "options",
        "code"
    ],
    mapper: {
        serializedName: "code",
        type: {
            name: "String"
        }
    }
};
export var grantType = {
    parameterPath: "grantType",
    mapper: {
        required: true,
        serializedName: "grant_type",
        type: {
            name: "String"
        }
    }
};
export var password = {
    parameterPath: [
        "options",
        "password"
    ],
    mapper: {
        serializedName: "password",
        type: {
            name: "String"
        }
    }
};
export var refreshToken = {
    parameterPath: [
        "options",
        "refreshToken"
    ],
    mapper: {
        serializedName: "refresh_token",
        type: {
            name: "String"
        }
    }
};
export var relayState = {
    parameterPath: "relayState",
    mapper: {
        required: true,
        serializedName: "RelayState",
        type: {
            name: "String"
        }
    }
};
export var sAMLResponse = {
    parameterPath: "sAMLResponse",
    mapper: {
        required: true,
        serializedName: "SAMLResponse",
        type: {
            name: "String"
        }
    }
};
export var tenantId = {
    parameterPath: "tenantId",
    mapper: {
        required: true,
        serializedName: "tenantId",
        type: {
            name: "String"
        }
    }
};
export var tid = {
    parameterPath: "tid",
    mapper: {
        required: true,
        serializedName: "tid",
        type: {
            name: "String"
        }
    }
};
export var userId = {
    parameterPath: "userId",
    mapper: {
        required: true,
        serializedName: "userId",
        type: {
            name: "String"
        }
    }
};
export var username = {
    parameterPath: [
        "options",
        "username"
    ],
    mapper: {
        serializedName: "username",
        type: {
            name: "String"
        }
    }
};
//# sourceMappingURL=parameters.js.map