/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The CompareRule model.
 */
public class CompareRule {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The version property.
     */
    @JsonProperty(value = "version")
    private Integer version;

    /**
     * The properties property.
     */
    @JsonProperty(value = "properties")
    private Map<String, PropertyCompareRule> properties;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the CompareRule object itself.
     */
    public CompareRule withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the version value.
     *
     * @return the version value
     */
    public Integer version() {
        return this.version;
    }

    /**
     * Set the version value.
     *
     * @param version the version value to set
     * @return the CompareRule object itself.
     */
    public CompareRule withVersion(Integer version) {
        this.version = version;
        return this;
    }

    /**
     * Get the properties value.
     *
     * @return the properties value
     */
    public Map<String, PropertyCompareRule> properties() {
        return this.properties;
    }

    /**
     * Set the properties value.
     *
     * @param properties the properties value to set
     * @return the CompareRule object itself.
     */
    public CompareRule withProperties(Map<String, PropertyCompareRule> properties) {
        this.properties = properties;
        return this;
    }

}
