/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.metabase.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Transform model.
 */
public class Transform {
    /**
     * The transformId property.
     */
    @JsonProperty(value = "transformId")
    private String transformId;

    /**
     * The format property.
     */
    @JsonProperty(value = "format")
    private String format;

    /**
     * Get the transformId value.
     *
     * @return the transformId value
     */
    public String transformId() {
        return this.transformId;
    }

    /**
     * Set the transformId value.
     *
     * @param transformId the transformId value to set
     * @return the Transform object itself.
     */
    public Transform withTransformId(String transformId) {
        this.transformId = transformId;
        return this;
    }

    /**
     * Get the format value.
     *
     * @return the format value
     */
    public String format() {
        return this.format;
    }

    /**
     * Set the format value.
     *
     * @param format the format value to set
     * @return the Transform object itself.
     */
    public Transform withFormat(String format) {
        this.format = format;
        return this;
    }

}
