/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.auth.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SamlGenerateRequestResponse model.
 */
public class SamlGenerateRequestResponse {
    /**
     * The relayState property.
     */
    @JsonProperty(value = "relay_state", required = true)
    private String relayState;

    /**
     * The samlRequest property.
     */
    @JsonProperty(value = "saml_request", required = true)
    private String samlRequest;

    /**
     * Get the relayState value.
     *
     * @return the relayState value
     */
    public String relayState() {
        return this.relayState;
    }

    /**
     * Set the relayState value.
     *
     * @param relayState the relayState value to set
     * @return the SamlGenerateRequestResponse object itself.
     */
    public SamlGenerateRequestResponse withRelayState(String relayState) {
        this.relayState = relayState;
        return this;
    }

    /**
     * Get the samlRequest value.
     *
     * @return the samlRequest value
     */
    public String samlRequest() {
        return this.samlRequest;
    }

    /**
     * Set the samlRequest value.
     *
     * @param samlRequest the samlRequest value to set
     * @return the SamlGenerateRequestResponse object itself.
     */
    public SamlGenerateRequestResponse withSamlRequest(String samlRequest) {
        this.samlRequest = samlRequest;
        return this;
    }

}
