/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.auth.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The UserAuthCodeResponse model.
 */
public class UserAuthCodeResponse {
    /**
     * The code property.
     */
    @JsonProperty(value = "code", required = true)
    private String code;

    /**
     * Get the code value.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the code value.
     *
     * @param code the code value to set
     * @return the UserAuthCodeResponse object itself.
     */
    public UserAuthCodeResponse withCode(String code) {
        this.code = code;
        return this;
    }

}
