/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.naveego.auth.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The UserLoginResponse model.
 */
public class UserLoginResponse {
    /**
     * The authCode property.
     */
    @JsonProperty(value = "auth_code")
    private String authCode;

    /**
     * The message property.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * The redirectUri property.
     */
    @JsonProperty(value = "redirect_uri")
    private String redirectUri;

    /**
     * The success property.
     */
    @JsonProperty(value = "success", required = true)
    private boolean success;

    /**
     * Get the authCode value.
     *
     * @return the authCode value
     */
    public String authCode() {
        return this.authCode;
    }

    /**
     * Set the authCode value.
     *
     * @param authCode the authCode value to set
     * @return the UserLoginResponse object itself.
     */
    public UserLoginResponse withAuthCode(String authCode) {
        this.authCode = authCode;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the UserLoginResponse object itself.
     */
    public UserLoginResponse withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the redirectUri value.
     *
     * @return the redirectUri value
     */
    public String redirectUri() {
        return this.redirectUri;
    }

    /**
     * Set the redirectUri value.
     *
     * @param redirectUri the redirectUri value to set
     * @return the UserLoginResponse object itself.
     */
    public UserLoginResponse withRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
        return this;
    }

    /**
     * Get the success value.
     *
     * @return the success value
     */
    public boolean success() {
        return this.success;
    }

    /**
     * Set the success value.
     *
     * @param success the success value to set
     * @return the UserLoginResponse object itself.
     */
    public UserLoginResponse withSuccess(boolean success) {
        this.success = success;
        return this;
    }

}
