// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Naveego.Metabase.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConnectionDiscoveredSchema
    {
        /// <summary>
        /// Initializes a new instance of the ConnectionDiscoveredSchema class.
        /// </summary>
        public ConnectionDiscoveredSchema()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConnectionDiscoveredSchema class.
        /// </summary>
        public ConnectionDiscoveredSchema(string discoveredSchemaId = default(string), bool? isAdvertised = default(bool?), string advertisedSchemaId = default(string))
        {
            DiscoveredSchemaId = discoveredSchemaId;
            IsAdvertised = isAdvertised;
            AdvertisedSchemaId = advertisedSchemaId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "discoveredSchemaId")]
        public string DiscoveredSchemaId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isAdvertised")]
        public bool? IsAdvertised { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "advertisedSchemaId")]
        public string AdvertisedSchemaId { get; set; }

    }
}
