// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Naveego.Metabase.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MergingPrerequisites
    {
        /// <summary>
        /// Initializes a new instance of the MergingPrerequisites class.
        /// </summary>
        public MergingPrerequisites()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MergingPrerequisites class.
        /// </summary>
        public MergingPrerequisites(IList<string> allRequiredConnectionIdsPresent = default(IList<string>), IList<string> oneConnectionIdMustBePresent = default(IList<string>))
        {
            AllRequiredConnectionIdsPresent = allRequiredConnectionIdsPresent;
            OneConnectionIdMustBePresent = oneConnectionIdMustBePresent;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "allRequiredConnectionIdsPresent")]
        public IList<string> AllRequiredConnectionIdsPresent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "oneConnectionIdMustBePresent")]
        public IList<string> OneConnectionIdMustBePresent { get; set; }

    }
}
