// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Naveego.Metabase.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for SecurityKeyStorage.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(SecurityKeyStorageConverter))]
    public struct SecurityKeyStorage : System.IEquatable<SecurityKeyStorage>
    {
        private SecurityKeyStorage(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        public static readonly SecurityKeyStorage Vault = "vault";

        public static readonly SecurityKeyStorage File = "file";


        /// <summary>
        /// Underlying value of enum SecurityKeyStorage
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for SecurityKeyStorage
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue == null ? null : UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type SecurityKeyStorage
        /// </summary>
        public bool Equals(SecurityKeyStorage e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to SecurityKeyStorage
        /// </summary>
        public static implicit operator SecurityKeyStorage(string value)
        {
            return new SecurityKeyStorage(value);
        }

        /// <summary>
        /// Implicit operator to convert SecurityKeyStorage to string
        /// </summary>
        public static implicit operator string(SecurityKeyStorage e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum SecurityKeyStorage
        /// </summary>
        public static bool operator == (SecurityKeyStorage e1, SecurityKeyStorage e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum SecurityKeyStorage
        /// </summary>
        public static bool operator != (SecurityKeyStorage e1, SecurityKeyStorage e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for SecurityKeyStorage
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is SecurityKeyStorage && Equals((SecurityKeyStorage)obj);
        }

        /// <summary>
        /// Returns for hashCode SecurityKeyStorage
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
