// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Naveego.Metabase.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ShapePropertySecurity
    {
        /// <summary>
        /// Initializes a new instance of the ShapePropertySecurity class.
        /// </summary>
        public ShapePropertySecurity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ShapePropertySecurity class.
        /// </summary>
        /// <param name="algorithm">Possible values include: 'none', 'aesgcm',
        /// 'sha256Hmac'</param>
        /// <param name="keyStorage">Possible values include: 'vault',
        /// 'file'</param>
        public ShapePropertySecurity(SecurityAlgorithm? algorithm = default(SecurityAlgorithm?), SecurityKeyStorage? keyStorage = default(SecurityKeyStorage?), string key = default(string))
        {
            Algorithm = algorithm;
            KeyStorage = keyStorage;
            Key = key;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'none', 'aesgcm',
        /// 'sha256Hmac'
        /// </summary>
        [JsonProperty(PropertyName = "algorithm")]
        public SecurityAlgorithm? Algorithm { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'vault', 'file'
        /// </summary>
        [JsonProperty(PropertyName = "keyStorage")]
        public SecurityKeyStorage? KeyStorage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

    }
}
