// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Naveego.Metabase.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Trace
    {
        /// <summary>
        /// Initializes a new instance of the Trace class.
        /// </summary>
        public Trace()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Trace class.
        /// </summary>
        public Trace(string n = default(string), System.DateTime? ts = default(System.DateTime?), int? d = default(int?))
        {
            N = n;
            Ts = ts;
            D = d;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "n")]
        public string N { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ts")]
        public System.DateTime? Ts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "d")]
        public int? D { get; set; }

    }
}
