import * as msRest from "ms-rest-js";
export declare const DiscoveryKey: msRest.CompositeMapper;
export declare const DiscoveryKeys: msRest.CompositeMapper;
export declare const OauthToken: msRest.CompositeMapper;
export declare const SamlGenerateRequestResponse: msRest.CompositeMapper;
export declare const SamlSAMLSettings: msRest.CompositeMapper;
export declare const TenantConfiguration: msRest.CompositeMapper;
export declare const UserAuthCodeResponse: msRest.CompositeMapper;
export declare const UserUser: msRest.CompositeMapper;
export declare const UserCreateUser: msRest.CompositeMapper;
export declare const AuthAPITokenOptionalParams: msRest.CompositeMapper;
